### ISSUE TITLE
jQuery.noConflict() compatibility

### ISSUE THREAD

**Issue by rdmiller** [tompi/jeoquery#1]
Please consider revising to be compatible with jQuery.noConflict().  I'd like to use this on an app that began as a prototype.js project that then needed some jQuery, so I ended up using both libraries, but the present $ shortcut is reserved for prototype and this code breaks.  Demo looks great, looking forward to using it.

**Comment by tompi** [comment]
Hi, I think it should work with noconflict now(I checked in a simple fix).

I really haven't spent much time tinkering with this,
made it just for the fun of it, so let me know if you run into
problems or need any changes.
