### ISSUE TITLE
Multiple country codes

### ISSUE THREAD

**Issue by vr55** [tompi/jeoquery#8]
Hello. How can i use multiple contry code in 'search' request?
i.e. "country=US&country=RU"

**Comment by tompi** [comment]
Hi. Just assign an array to "country" param, like this:

``` javascript
jeoquery.getGeoNames('countryInfo', { country: ['GB', 'NO'] }, function(countries) {
    console.log(countries.length); 
});
```

Latest version uses jquery ajax param "traditional=true" so this serializes to "country=GB&country=NO" instead of "country[]=GB&country[]=NO".
